
[build]
  # This tells Netlify which folder to publish.
  # All your HTML, CSS, and JS files should be in here.
  publish = "frontend/"
  
  # No build command needed for static HTML/CSS/JS
  command = ""

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
