services:
  - type: web
    name: code-craft-backend
    env: docker
    dockerfilePath: Backend/Dockerfile
    buildCommand: ""
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8080 app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "8080"
    plan: free
